name: Deploy to ECS

on:
  push: 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to AWS ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ap-northeast-2
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 272440905989.dkr.ecr.ap-northeast-2.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t hangman .
          docker tag hangman:latest 272440905989.dkr.ecr.ap-northeast-2.amazonaws.com/hangman:latest

      - name: Push to AWS ECR
        run: |
          docker push 272440905989.dkr.ecr.ap-northeast-2.amazonaws.com/hangman:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster hangman --service hangman --force-new-deployment
